//
// SheepCompiler.h
//
// Clark Kromenaker
//
// Capable of taking sheep in text format and compiling it to a binary SheepScript asset.
// Uses the Sheep scanner/parser generated by Flex/Bison respectively.
//
#pragma once
#include <istream>
#include <map>
#include <string>

#include "SheepScanner.h"
#include "sheep.tab.hh"

class SheepScript;

class SheepCompiler
{
public:
    SheepCompiler() = default;
    virtual ~SheepCompiler();
    
    SheepScript* Compile(const char* filename);
    SheepScript* Compile(const std::string& sheep);
    SheepScript* Compile(std::istream& stream);
	
    void Error(const Sheep::location& location, const std::string& message);
    
private:
    SheepScanner* mScanner = nullptr;
    Sheep::Parser* mParser = nullptr;
    
    void DebugOutputTokens(SheepScanner* scanner);
};
